/**
 * Generates the local-only deployment wallets and writes them into the
 * repository-root .env (which .gitignore already excludes).
 *
 * SAFETY CONTRACT:
 *   - Private keys are written to disk at ./.env and NOWHERE else.
 *   - Private keys are never printed to stdout/stderr, never logged, and
 *     never placed in any file git tracks.
 *   - Existing keys are never overwritten; re-running is a safe no-op that
 *     just re-prints the public addresses.
 *
 * Usage: pnpm --filter @alive/contracts init:deployer
 */
import { appendFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

/**
 * Walks up from the working directory to the workspace root (the directory
 * holding pnpm-workspace.yaml) so this behaves identically whether it is
 * invoked from the repo root or from packages/contracts. Avoids import.meta,
 * which this package's CommonJS tsconfig disallows.
 */
function findRepoRoot(): string {
  let current = process.cwd();
  for (let depth = 0; depth < 8; depth += 1) {
    if (existsSync(path.join(current, "pnpm-workspace.yaml"))) return current;
    const parent = path.dirname(current);
    if (parent === current) break;
    current = parent;
  }
  throw new Error("Could not locate the workspace root (pnpm-workspace.yaml)");
}

const envPath = path.join(findRepoRoot(), ".env");

const MANAGED_KEYS = [
  "DEPLOYER_PRIVATE_KEY",
  "ELIGIBILITY_SIGNER_PRIVATE_KEY",
] as const;
type ManagedKey = (typeof MANAGED_KEYS)[number];

function readEnvFile(): Map<string, string> {
  const values = new Map<string, string>();
  if (!existsSync(envPath)) return values;
  for (const line of readFileSync(envPath, "utf8").split(/\r?\n/u)) {
    const match = /^([A-Z0-9_]+)=(.*)$/u.exec(line.trim());
    if (match?.[1] !== undefined && match[2] !== undefined) {
      values.set(match[1], match[2]);
    }
  }
  return values;
}

function main(): void {
  const existing = readEnvFile();
  if (!existsSync(envPath)) {
    writeFileSync(
      envPath,
      "# ALIVE local secrets. Never commit this file.\n" +
        "# Generated by packages/contracts/scripts/init-deployer.ts\n",
      { mode: 0o600 },
    );
  }

  const created: ManagedKey[] = [];
  for (const key of MANAGED_KEYS) {
    const current = existing.get(key)?.trim();
    if (current && /^0x[0-9a-fA-F]{64}$/.test(current)) continue;
    if (current) {
      throw new Error(
        `${key} already exists in .env but is not a valid 32-byte hex key. Fix or remove it manually; refusing to overwrite.`,
      );
    }
    appendFileSync(envPath, `${key}=${generatePrivateKey()}\n`, { mode: 0o600 });
    created.push(key);
  }

  // Re-read so addresses are always derived from what is actually on disk.
  const finalValues = readEnvFile();
  const deployerKey = finalValues.get("DEPLOYER_PRIVATE_KEY");
  const signerKey = finalValues.get("ELIGIBILITY_SIGNER_PRIVATE_KEY");
  if (!deployerKey || !signerKey) {
    throw new Error("Failed to persist deployment keys to .env");
  }

  const deployer = privateKeyToAccount(deployerKey as `0x${string}`).address;
  const signer = privateKeyToAccount(signerKey as `0x${string}`).address;

  process.stdout.write(
    created.length > 0
      ? `\nGenerated ${created.length} new key(s) in .env (gitignored).\n`
      : `\nReusing the existing keys already present in .env.\n`,
  );
  process.stdout.write(`\nTESTNET DEPLOYER WALLET\n${deployer}\n`);
  process.stdout.write(`\nELIGIBILITY SIGNER WALLET\n${signer}\n`);
  process.stdout.write(
    `\nOnly the deployer needs X Layer Testnet OKB for gas.\n` +
      `The eligibility signer signs EIP-712 verdicts offchain and needs no balance.\n`,
  );
}

main();
