/**
 * Generates apps/web/.env.local from a deployment record, so the frontend
 * points at real deployed addresses instead of hand-copied ones.
 *
 * Reads packages/contracts/deployments/rwa-<chainId>.json and writes the
 * NEXT_PUBLIC_* variables apps/web/lib/rwa-chain.ts actually consumes.
 * Refuses to invent an address: if the record is missing a contract the
 * frontend requires, it fails loudly rather than emitting a blank.
 *
 * Usage:
 *   pnpm --filter @alive/contracts sync:web-env 1952
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type Entry = { address: string };
type Record_ = {
  chainId: number;
  contracts: Record<string, Entry>;
  demoOnlyContracts?: Record<string, Entry>;
  assetIds?: Record<string, string>;
};

function findRepoRoot(): string {
  let current = process.cwd();
  for (let depth = 0; depth < 8; depth += 1) {
    if (existsSync(path.join(current, "pnpm-workspace.yaml"))) return current;
    const parent = path.dirname(current);
    if (parent === current) break;
    current = parent;
  }
  throw new Error("Could not locate the workspace root (pnpm-workspace.yaml)");
}

const CHAIN_ENV: Record<number, string> = {
  31337: "local",
  1952: "xlayer-testnet",
  196: "xlayer-mainnet",
};

function main(): void {
  const chainId = Number(process.argv[2] ?? "1952");
  if (!Number.isInteger(chainId)) throw new Error("Pass a numeric chain ID");

  const repoRoot = findRepoRoot();
  const recordPath = path.join(
    repoRoot,
    "packages/contracts/deployments",
    `rwa-${chainId}.json`,
  );
  if (!existsSync(recordPath)) {
    throw new Error(
      `No deployment record at ${recordPath}. Deploy first; this script never fabricates addresses.`,
    );
  }
  const record = JSON.parse(readFileSync(recordPath, "utf8")) as Record_;
  if (record.chainId !== chainId) {
    throw new Error(
      `Record chainId ${record.chainId} does not match requested ${chainId}`,
    );
  }

  const all = { ...record.contracts, ...(record.demoOnlyContracts ?? {}) };
  function need(name: string): string {
    const entry = all[name];
    if (!entry?.address) {
      throw new Error(`Deployment record is missing required contract ${name}`);
    }
    return entry.address;
  }

  const chainEnv = CHAIN_ENV[chainId];
  if (!chainEnv) throw new Error(`Unknown chain ID ${chainId}`);

  const lines = [
    "# Generated by packages/contracts/scripts/sync-web-env.ts",
    `# Source: deployments/rwa-${chainId}.json -- do not hand-edit addresses.`,
    "",
    `NEXT_PUBLIC_CHAIN_ENV=${chainEnv}`,
    `NEXT_PUBLIC_INTELLIGENCE_URL=${process.env.NEXT_PUBLIC_INTELLIGENCE_URL ?? "http://127.0.0.1:4200"}`,
    "",
    `NEXT_PUBLIC_RWA_ASSET_REGISTRY_ADDRESS=${need("AliveRwaAssetRegistry")}`,
    `NEXT_PUBLIC_ELIGIBILITY_REGISTRY_ADDRESS=${need("AliveEligibilityRegistry")}`,
    `NEXT_PUBLIC_POLICY_REGISTRY_ADDRESS=${need("AlivePolicyRegistry")}`,
    `NEXT_PUBLIC_STRATEGY_VERIFIER_ADDRESS=${need("AliveStrategyVerifier")}`,
    `NEXT_PUBLIC_RWA_VAULT_FACTORY_ADDRESS=${need("AliveVaultFactory")}`,
    `NEXT_PUBLIC_RWA_VAULT_ADDRESS=${need("AliveVault")}`,
    `NEXT_PUBLIC_RWA_ROUTER_ADDRESS=${need("MockRwaRouter")}`,
    `NEXT_PUBLIC_RWA_CASH_TOKEN_ADDRESS=${need("MockRwaToken:tusdc")}`,
    `NEXT_PUBLIC_RWA_FAUCET_ADDRESS=${need("DemoRwaFaucet")}`,
    "",
    "# Primary demo asset for the verification gateway walkthrough.",
    `NEXT_PUBLIC_DEMO_ASSET_ID=ttbill-a`,
    `NEXT_PUBLIC_DEMO_ASSET_TOKEN_ADDRESS=${need("MockRwaToken:ttbill-a")}`,
    "",
  ];

  const outputPath = path.join(repoRoot, "apps/web/.env.local");
  writeFileSync(outputPath, `${lines.join("\n")}\n`, "utf8");
  process.stdout.write(`Wrote ${outputPath} from rwa-${chainId}.json\n`);
  process.stdout.write(`  chain env  ${chainEnv} (chainId ${chainId})\n`);
  process.stdout.write(
    `  contracts  ${Object.keys(record.contracts).length} core, ${Object.keys(record.demoOnlyContracts ?? {}).length} demo-only\n`,
  );
}

main();
