packages:
  - apps/*
  - services/*
  - packages/*
  - videos/*

allowBuilds:
  better-sqlite3: true
  esbuild: true
  keccak: true
  onnxruntime-node: true
  protobufjs: true
  secp256k1: true
  sharp: true
  tesseract.js: true
